# Generated by Django 4.0.5 on 2022-06-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_rewiew_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewiew',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
